#!/bin/bash
#PBS -q voltaq
#PBS -l select=1:ngpus=1
#PBS -l walltime=00:10:00
#PBS -l place=excl
#PBS -joe

set -eu

cd "$RUN_DIR" || exit 2
date
echo "$PWD"
ldd "$BENCHMARK_EXE"

opts=("all" "268435456")

case "$MODEL" in
omp | std-* | cuda | kokkos | chapel)
    "$BENCHMARK_EXE" --list
    "$BENCHMARK_EXE" "${opts[@]:-}"
    ;;
*)
    echo "Unknown run configuration for model '$MODEL'"
    exit 1
    ;;
esac

